### ISSUE TITLE
TypeError: argument of type 'NoneType' is not iterable

### ISSUE THREAD

**Issue by abraskic** [BrodieSutherland/up-to-ynab#9]
> 2023-01-17T02:11:13.594614+00:00 app[web.1]: Setting up Payee->Category Databases...
2023-01-17T02:11:15.262539+00:00 app[web.1]: Traceback (most recent call last):
2023-01-17T02:11:15.262558+00:00 app[web.1]:   File "/app/main.py", line 34, in <module>
2023-01-17T02:11:15.262695+00:00 app[web.1]:     helper.setAllYNABDatabases()
2023-01-17T02:11:15.262710+00:00 app[web.1]:   File "/app/helper.py", line 111, in setAllYNABDatabases
2023-01-17T02:11:15.262836+00:00 app[web.1]:     budget = classes.YNABBudget(response.json()["data"]["budget"])
2023-01-17T02:11:15.262847+00:00 app[web.1]:   File "/app/classes.py", line 327, in __init__
2023-01-17T02:11:15.263011+00:00 app[web.1]:     self.setPayeeCategoryDatabase()
2023-01-17T02:11:15.263022+00:00 app[web.1]:   File "/app/classes.py", line 352, in setPayeeCategoryDatabase
2023-01-17T02:11:15.263182+00:00 app[web.1]:     and "Transfer : " not in transaction.payeeName
2023-01-17T02:11:15.263210+00:00 app[web.1]: TypeError: argument of type 'NoneType' is not iterable

Trying to run the app I get this error. Not even sure where to start troubleshooting.

**Comment by BrodieSutherland** [comment]
Hi! Looks like the `transactions` list in the `YNABBudget` class is None instead of a list of transactions :thinking: 

Can I just confirm that your YNAB Budget you've got set up has some pre-existing transactions? Or is it a brand new budget?

**Comment by abraskic** [comment]
Nope, same budget I've been using for the past five years. Could it potentially be the name of the Up account on my budget? I did change it to Spending as per the instructions.

**Comment by BrodieSutherland** [comment]
I wouldn't think so, the bit it's failing on according to the stack trace is when it tries to generate the YNAB Payee -> YNAB category map/database, so it should all be from YNAB at this point, but i think the thing I'm looking at is that it's the first time it tries to parse the YNAB payload, so that's probably the problem. Could you provide your `.env` file (change a few numbers and letters tho just to be safe)? I'll give an example below (i should prob also add an example in the repo too):

```
budgetId=0c8u2981-c89d-4ff9-8213-622778602665
BASE_URL=https://somelink.com
PORT=5000
upKey=up:yeah:RN3b5FfTD4yv3qHRgKThFjZJKyKasdasdasdOasdadXmzP6aGhQeJmogkwmQ0EaZ4aE1xlsFjN9cd5nbxTg6Jn238iF06u3b3tfasdasdRPgaxVQ4sAasdasdKZGz4HThCrg
ynabKey=b903f5fd1fbadasd0d03e3638b0cf6334567459ee31db387cse13616ca3b4295a
```
